#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Vietnamese to Persian (Farsi) Translation Script
Translates ALL 3168 keys from vi.json to fa.json
"""

import json
import re
from typing import Dict, Any

# Massive Vietnamese to Persian Translation Dictionary
TRANSLATION_DICT = {
    # Common Actions
    "thêm": "افزودن",
    "Thêm": "افزودن",
    "xóa": "حذف",
    "Xóa": "حذف",
    "sửa": "ویرایش",
    "Sửa": "ویرایش",
    "lưu": "ذخیره",
    "Lưu": "ذخیره",
    "cập nhật": "به‌روزرسانی",
    "Cập nhật": "به‌روزرسانی",
    "tạo": "ایجاد",
    "Tạo": "ایجاد",
    "tìm kiếm": "جستجو",
    "Tìm kiếm": "جستجو",
    "tải": "بارگذاری",
    "Tải": "بارگذاری",
    "tải lên": "آپلود",
    "tải xuống": "دانلود",
    "gửi": "ارسال",
    "Gửi": "ارسال",
    "nhận": "دریافت",
    "Nhận": "دریافت",
    "xác nhận": "تأیید",
    "Xác nhận": "تأیید",
    "hủy": "لغو",
    "Hủy": "لغو",
    "đóng": "بستن",
    "Đóng": "بستن",
    "mở": "باز کردن",
    "Mở": "باز کردن",
    "bật": "فعال کردن",
    "Bật": "فعال کردن",
    "tắt": "غیرفعال کردن",
    "Tắt": "غیرفعال کردن",
    "kích hoạt": "فعال‌سازی",
    "Kích hoạt": "فعال‌سازی",
    "vô hiệu hóa": "غیرفعال‌سازی",
    "Vô hiệu hóa": "غیرفعال‌سازی",
    "chọn": "انتخاب",
    "Chọn": "انتخاب",
    "xem": "مشاهده",
    "Xem": "مشاهده",
    "hiển thị": "نمایش",
    "Hiển thị": "نمایش",
    "ẩn": "مخفی",
    "Ẩn": "مخفی",
    "chỉnh sửa": "ویرایش",
    "Chỉnh sửa": "ویرایش",
    "sao chép": "کپی",
    "Sao chép": "کپی",
    "dán": "چسباندن",
    "Dán": "چسباندن",
    "di chuyển": "انتقال",
    "Di chuyển": "انتقال",
    "làm mới": "تازه‌سازی",
    "Làm mới": "تازه‌سازی",
    "đặt lại": "بازنشانی",
    "Đặt lại": "بازنشانی",
    "xuất": "صادر کردن",
    "Xuất": "صادر کردن",
    "nhập": "وارد کردن",
    "Nhập": "وارد کردن",
    "khôi phục": "بازیابی",
    "Khôi phục": "بازیابی",
    "sao lưu": "پشتیبان‌گیری",
    "Sao lưu": "پشتیبان‌گیری",
    "phục hồi": "بازیابی",
    "Phục hồi": "بازیابی",
    "kiểm tra": "بررسی",
    "Kiểm tra": "بررسی",
    "thử nghiệm": "آزمایش",
    "Thử nghiệm": "آزمایش",
    "kiểm thử": "تست",
    "Kiểm thử": "تست",
    "chạy": "اجرا",
    "Chạy": "اجرا",
    "dừng": "توقف",
    "Dừng": "توقف",
    "khởi động": "راه‌اندازی",
    "Khởi động": "راه‌اندازی",
    "khởi động lại": "راه‌اندازی مجدد",
    "Khởi động lại": "راه‌اندازی مجدد",
    "kết nối": "اتصال",
    "Kết nối": "اتصال",
    "ngắt kết nối": "قطع اتصال",
    "Ngắt kết nối": "قطع اتصال",
    
    # UI Elements
    "nút": "دکمه",
    "Nút": "دکمه",
    "trang": "صفحه",
    "Trang": "صفحه",
    "danh sách": "لیست",
    "Danh sách": "لیست",
    "menu": "منو",
    "Menu": "منو",
    "thanh": "نوار",
    "Thanh": "نوار",
    "hộp": "جعبه",
    "Hộp": "جعبه",
    "cửa sổ": "پنجره",
    "Cửa sổ": "پنجره",
    "hộp thoại": "دیالوگ",
    "Hộp thoại": "دیالوگ",
    "biểu mẫu": "فرم",
    "Biểu mẫu": "فرم",
    "trường": "فیلد",
    "Trường": "فیلد",
    "nhãn": "برچسب",
    "Nhãn": "برچسب",
    "tiêu đề": "عنوان",
    "Tiêu đề": "عنوان",
    "mô tả": "توضیحات",
    "Mô tả": "توضیحات",
    "thông báo": "اعلان",
    "Thông báo": "اعلان",
    "cảnh báo": "هشدار",
    "Cảnh báo": "هشدار",
    "lỗi": "خطا",
    "Lỗi": "خطا",
    "thành công": "موفقیت",
    "Thành công": "موفقیت",
    "thất bại": "ناموفق",
    "Thất bại": "ناموفق",
    "đang tải": "در حال بارگذاری",
    "Đang tải": "در حال بارگذاری",
    "đang xử lý": "در حال پردازش",
    "Đang xử lý": "در حال پردازش",
    "hoàn thành": "تکمیل شده",
    "Hoàn thành": "تکمیل شده",
    "đang chờ": "در انتظار",
    "Đang chờ": "در انتظار",
    
    # Status
    "trạng thái": "وضعیت",
    "Trạng thái": "وضعیت",
    "hoạt động": "فعال",
    "Hoạt động": "فعال",
    "không hoạt động": "غیرفعال",
    "Không hoạt động": "غیرفعال",
    "trực tuyến": "آنلاین",
    "Trực tuyến": "آنلاین",
    "ngoại tuyến": "آفلاین",
    "Ngoại tuyến": "آفلاین",
    "bình thường": "عادی",
    "Bình thường": "عادی",
    "sẵn sàng": "آماده",
    "Sẵn sàng": "آماده",
    "bận": "مشغول",
    "Bận": "مشغول",
    
    # Common Terms
    "tên": "نام",
    "Tên": "نام",
    "mật khẩu": "رمز عبور",
    "Mật khẩu": "رمز عبور",
    "email": "ایمیل",
    "Email": "ایمیل",
    "người dùng": "کاربر",
    "Người dùng": "کاربر",
    "quản trị viên": "مدیر",
    "Quản trị viên": "مدیر",
    "vai trò": "نقش",
    "Vai trò": "نقش",
    "quyền": "مجوز",
    "Quyền": "مجوز",
    "nhóm": "گروه",
    "Nhóm": "گروه",
    "loại": "نوع",
    "Loại": "نوع",
    "phân loại": "دسته‌بندی",
    "Phân loại": "دسته‌بندی",
    "danh mục": "دسته",
    "Danh mục": "دسته",
    "số lượng": "تعداد",
    "Số lượng": "تعداد",
    "giá trị": "مقدار",
    "Giá trị": "مقدار",
    "giá": "قیمت",
    "Giá": "قیمت",
    "chi phí": "هزینه",
    "Chi phí": "هزینه",
    "tổng": "جمع",
    "Tổng": "جمع",
    "tổng cộng": "مجموع",
    "Tổng cộng": "مجموع",
    "số dư": "موجودی",
    "Số dư": "موجودی",
    "hạn mức": "سقف",
    "Hạn mức": "سقف",
    "ngưỡng": "آستانه",
    "Ngưỡng": "آستانه",
    "giới hạn": "محدودیت",
    "Giới hạn": "محدودیت",
    "tối đa": "حداکثر",
    "Tối đa": "حداکثر",
    "tối thiểu": "حداقل",
    "Tối thiểu": "حداقل",
    "mặc định": "پیش‌فرض",
    "Mặc định": "پیش‌فرض",
    "tùy chọn": "گزینه",
    "Tùy chọn": "گزینه",
    "cài đặt": "تنظیمات",
    "Cài đặt": "تنظیمات",
    "cấu hình": "پیکربندی",
    "Cấu hình": "پیکربندی",
    "thiết lập": "تنظیم",
    "Thiết lập": "تنظیم",
    
    # Time
    "thời gian": "زمان",
    "Thời gian": "زمان",
    "ngày": "روز",
    "Ngày": "روز",
    "tháng": "ماه",
    "Tháng": "ماه",
    "năm": "سال",
    "Năm": "سال",
    "giờ": "ساعت",
    "Giờ": "ساعت",
    "phút": "دقیقه",
    "Phút": "دقیقه",
    "giây": "ثانیه",
    "Giây": "ثانیه",
    "tuần": "هفته",
    "Tuần": "هفته",
    "hôm nay": "امروز",
    "Hôm nay": "امروز",
    "hôm qua": "دیروز",
    "Hôm qua": "دیروز",
    "ngày mai": "فردا",
    "Ngày mai": "فردا",
    "hiện tại": "فعلی",
    "Hiện tại": "فعلی",
    "trước": "قبل",
    "Trước": "قبل",
    "sau": "بعد",
    "Sau": "بعد",
    
    # Common Phrases
    "vui lòng": "لطفاً",
    "Vui lòng": "لطفاً",
    "xin chào": "سلام",
    "Xin chào": "سلام",
    "cảm ơn": "متشکرم",
    "Cảm ơn": "متشکرم",
    "xin lỗi": "متأسفم",
    "Xin lỗi": "متأسفم",
    "có": "بله",
    "Có": "بله",
    "không": "خیر",
    "Không": "خیر",
    "đúng": "درست",
    "Đúng": "درست",
    "sai": "نادرست",
    "Sai": "نادرست",
    "được": "موافق",
    "Được": "موافق",
    "không được": "غیرقابل قبول",
    "Không được": "غیرقابل قبول",
    
    # Technical Terms (Vietnamese to Persian)
    "mô hình": "مدل",
    "Mô hình": "مدل",
    "kênh": "کانال",
    "Kênh": "کانال",
    "mã thông báo": "توکن",
    "Mã thông báo": "توکن",
    "khóa": "کلید",
    "Khóa": "کلید",
    "điểm cuối": "اندپوینت",
    "Điểm cuối": "اندپوینت",
    "địa chỉ": "آدرس",
    "Địa chỉ": "آدرس",
    "yêu cầu": "درخواست",
    "Yêu cầu": "درخواست",
    "phản hồi": "پاسخ",
    "Phản hồi": "پاسخ",
    "phiên bản": "نسخه",
    "Phiên bản": "نسخه",
    "giao diện": "رابط",
    "Giao diện": "رابط",
    "dịch vụ": "سرویس",
    "Dịch vụ": "سرویس",
    "máy chủ": "سرور",
    "Máy chủ": "سرور",
    "cơ sở dữ liệu": "پایگاه داده",
    "Cơ sở dữ liệu": "پایگاه داده",
    "hệ thống": "سیستم",
    "Hệ thống": "سیستم",
    "ứng dụng": "برنامه",
    "Ứng dụng": "برنامه",
    "chương trình": "نرم‌افزار",
    "Chương trình": "نرم‌افزار",
    "tài liệu": "مستندات",
    "Tài liệu": "مستندات",
    "tập tin": "فایل",
    "Tập tin": "فایل",
    "tệp": "فایل",
    "Tệp": "فایل",
    "thư mục": "پوشه",
    "Thư mục": "پوشه",
    "đường dẫn": "مسیر",
    "Đường dẫn": "مسیر",
    "liên kết": "لینک",
    "Liên kết": "لینک",
    "kết quả": "نتیجه",
    "Kết quả": "نتیجه",
    "dữ liệu": "داده",
    "Dữ liệu": "داده",
    "thông tin": "اطلاعات",
    "Thông tin": "اطلاعات",
    "chi tiết": "جزئیات",
    "Chi tiết": "جزئیات",
    "mô tả chi tiết": "شرح کامل",
    "Mô tả chi tiết": "شرح کامل",
    
    # Management
    "quản lý": "مدیریت",
    "Quản lý": "مدیریت",
    "giám sát": "نظارت",
    "Giám sát": "نظارت",
    "theo dõi": "پیگیری",
    "Theo dõi": "پیگیری",
    "phân tích": "تحلیل",
    "Phân tích": "تحلیل",
    "thống kê": "آمار",
    "Thống kê": "آمار",
    "báo cáo": "گزارش",
    "Báo cáo": "گزارش",
    "bảng điều khiển": "داشبورد",
    "Bảng điều khiển": "داشبورد",
    "tổng quan": "نمای کلی",
    "Tổng quan": "نمای کلی",
    
    # Messages
    "tin nhắn": "پیام",
    "Tin nhắn": "پیام",
    "thông điệp": "پیام",
    "Thông điệp": "پیام",
    "nhắc nhở": "یادآوری",
    "Nhắc nhở": "یادآوری",
    "đề xuất": "پیشنهاد",
    "Đề xuất": "پیشنهاد",
    "gợi ý": "راهنمایی",
    "Gợi ý": "راهنمایی",
    "hướng dẫn": "دستورالعمل",
    "Hướng dẫn": "دستورالعمل",
    "trợ giúp": "کمک",
    "Trợ giúp": "کمک",
    "hỗ trợ": "پشتیبانی",
    "Hỗ trợ": "پشتیبانی",
    
    # Specific Terms
    "trò chuyện": "گفتگو",
    "Trò chuyện": "گفتگو",
    "hội thoại": "مکالمه",
    "Hội thoại": "مکالمه",
    "cuộc trò chuyện": "چت",
    "Cuộc trò chuyện": "چت",
    "hình ảnh": "تصویر",
    "Hình ảnh": "تصویر",
    "ảnh": "عکس",
    "Ảnh": "عکس",
    "video": "ویدئو",
    "Video": "ویدئو",
    "âm thanh": "صدا",
    "Âm thanh": "صدا",
    "văn bản": "متن",
    "Văn bản": "متن",
    "nội dung": "محتوا",
    "Nội dung": "محتوا",
    "đầu vào": "ورودی",
    "Đầu vào": "ورودی",
    "đầu ra": "خروجی",
    "Đầu ra": "خروجی",
    "nhập liệu": "ورودی",
    "Nhập liệu": "ورودی",
    "xuất liệu": "خروجی",
    "Xuất liệu": "خروجی",
    
    # Numbers and Units
    "lần": "بار",
    "Lần": "بار",
    "lượt": "نوبت",
    "Lượt": "نوبت",
    "cái": "عدد",
    "Cái": "عدد",
    "chiếc": "دستگاه",
    "Chiếc": "دستگاه",
    "người": "نفر",
    "Người": "نفر",
    
    # Specific App Terms
    "nạp tiền": "شارژ",
    "Nạp tiền": "شارژ",
    "thanh toán": "پرداخت",
    "Thanh toán": "پرداخت",
    "đăng nhập": "ورود",
    "Đăng nhập": "ورود",
    "đăng xuất": "خروج",
    "Đăng xuất": "خروج",
    "đăng ký": "ثبت‌نام",
    "Đăng ký": "ثبت‌نام",
    "tài khoản": "حساب کاربری",
    "Tài khoản": "حساب کاربری",
    "hồ sơ": "پروفایل",
    "Hồ sơ": "پروفایل",
    
    # Special Characters
    " không?": " نه؟",
    " không!": " نه!",
    " không.": " نیست.",
    " không": " نه",
    " phải không?": " درست است؟",
    
    # More specific phrases
    "Đã đăng nhập hôm nay": "امروز وارد شده‌اید",
    "đã đăng nhập hôm nay": "امروز وارد شده‌اید",
    "Hạn ngạch phải lớn hơn": "سقف باید بیشتر از",
    "phải lớn hơn": "باید بیشتر از",
    "phải lớn hơn hoặc bằng": "باید بیشتر یا مساوی با",
    "phải là số dương": "باید عدد مثبت باشد",
    "Giá trị tối đa": "حداکثر مقدار",
    "Giá trị tối thiểu": "حداقل مقدار",
    "không thể": "نمی‌توان",
    "Không thể": "نمی‌توان",
    "không được": "مجاز نیست",
    "Không được": "مجاز نیست",
    "Số thập phân giữa": "عدد اعشاری بین",
    "Số thập phân trên": "عدد اعشاری بالای",
    
    # More Action verbs
    "nhấn": "کلیک کنید",
    "Nhấn": "کلیک کنید",
    "nhấn để": "برای کلیک کنید",
    "Nhấn để": "برای کلیک کنید",
    "nhấn chuột": "کلیک",
    "Nhấn chuột": "کلیک",
    "kéo": "کشیدن",
    "Kéo": "کشیدن",
    "thả": "رها کردن",
    "Thả": "رها کردن",
    
    # Additional UI
    "màu sắc": "رنگ",
    "Màu sắc": "رنگ",
    "kích thước": "اندازه",
    "Kích thước": "اندازه",
    "vị trí": "موقعیت",
    "Vị trí": "موقعیت",
    "góc": "گوشه",
    "Góc": "گوشه",
    "trên": "بالا",
    "Trên": "بالا",
    "dưới": "پایین",
    "Dưới": "پایین",
    "trái": "چپ",
    "Trái": "چپ",
    "phải": "راست",
    "Phải": "راست",
    "giữa": "وسط",
    "Giữa": "وسط",
    
    # More status terms
    "đang chạy": "در حال اجرا",
    "Đang chạy": "در حال اجرا",
    "đã dừng": "متوقف شده",
    "Đã dừng": "متوقف شده",
    "đã hoàn thành": "تکمیل شده",
    "Đã hoàn thành": "تکمیل شده",
    "chưa hoàn thành": "ناتمام",
    "Chưa hoàn thành": "ناتمام",
    "đang chờ xử lý": "در انتظار پردازش",
    "Đang chờ xử lý": "در انتظار پردازش",
    
    # Model/AI specific
    "mô hình AI": "مدل هوش مصنوعی",
    "Mô hình AI": "مدل هوش مصنوعی",
    "mô hình thử nghiệm": "مدل آزمایشی",
    "Mô hình thử nghiệm": "مدل آزمایشی",
    "môi trường thử nghiệm": "محیط آزمایش",
    "Môi trường thử nghiệm": "محیط آزمایش",
    "tỷ lệ": "نسبت",
    "Tỷ lệ": "نسبت",
    "tỷ lệ hoàn thành": "نرخ تکمیل",
    "Tỷ lệ hoàn thành": "نرخ تکمیل",
    "bộ nhớ đệm": "کش",
    "Bộ nhớ đệm": "کش",
    
    # More common words
    "nhưng": "اما",
    "Nhưng": "اما",
    "hoặc": "یا",
    "Hoặc": "یا",
    "và": "و",
    "Và": "و",
    "của": "از",
    "Của": "از",
    "cho": "برای",
    "Cho": "برای",
    "với": "با",
    "Với": "با",
    "từ": "از",
    "Từ": "از",
    "đến": "به",
    "Đến": "به",
    "trong": "در",
    "Trong": "در",
    "ngoài": "خارج",
    "Ngoài": "خارج",
    "trên": "روی",
    "dưới": "زیر",
    
    # More Vietnamese words from the file
    "các": "",  # Often prefix, remove
    "Các": "",  # Often prefix, remove
    "Gọi": "فراخوانی",
    "gọi": "فراخوانی",
    "Tìm": "جستجو",
    "tìm": "جستجو",
    "Web": "وب",
    "Tạo": "ایجاد",
    "tạo": "ایجاد",
    "có cùng": "یکسان دارند",
    "nhấn để cập nhật": "برای به‌روزرسانی کلیک کنید",
    "Hiện tại chỉ hỗ trợ": "در حال حاضر فقط پشتیبانی می‌شود",
    "địa chỉ máy chủ": "آدرس سرور",
    "được sử dụng làm": "به عنوان استفاده می‌شود",
    "theo mặc định": "به طور پیش‌فرض",
    "sau khi lọc": "بعد از فیلتر",
    "sau ngày": "بعد از تاریخ",
    "không cần": "نیازی نیست",
    "khi triển khai": "هنگام استقرار",
    "dấu chấm": "نقطه",
    "trong tên": "در نام",
    "thấp nhất": "کمترین",
    "cao nhất": "بیشترین",
    "Thấp nhất": "کمترین",
    "Cao nhất": "بیشترین",
    "Thấp": "کم",
    "thấp": "کم",
    "Cao": "زیاد",
    "cao": "زیاد",
    "Bình thường": "معمولی",
    "bình thường": "معمولی",
    "Giấy phép": "مجوز",
    "giấy phép": "مجوز",
    "Chế độ": "حالت",
    "chế độ": "حالت",
    "sử dụng": "استفاده",
    "Sử dụng": "استفاده",
    "Không hỗ trợ": "پشتیبانی نمی‌شود",
    "không hỗ trợ": "پشتیبانی نمی‌شود",
    "hàng loạt": "انبوه",
    "Hàng loạt": "انبوه",
    "thành công": "موفق",
    "Thành công": "موفق",
    "thất bại": "ناموفق",
    "Thất bại": "ناموفق",
    "Kết nối": "اتصال",
    "kết nối": "اتصال",
    "bình thường": "عادی",
    "Quản lý": "مدیریت",
    "quản lý": "مدیریت",
    "có thể": "می‌توان",
    "Có thể": "می‌توان",
    "nhiều": "چندین",
    "Nhiều": "چندین",
    "để": "برای",
    "Để": "برای",
    "cân bằng tải": "توازن بار",
    "Cân bằng tải": "توازن بار",
    "tối đa": "حداکثر",
    "Tối đa": "حداکثر",
    "Điền": "پر کردن",
    "điền": "پر کردن",
    "ủy quyền": "مجوز دهی",
    "Ủy quyền": "مجوز دهی",
    "gọi lại": "بازگشت",
    "Gọi lại": "بازگشت",
    "chuỗi": "زنجیره",
    "Chuỗi": "زنجیره",
    "tự động": "خودکار",
    "Tự động": "خودکار",
    "đẩy": "فشار",
    "Đẩy": "فشار",
    "phải bắt đầu bằng": "باید با شروع شود",
    "Đang thay đổi": "در حال تغییر",
    "đang thay đổi": "در حال تغییر",
    "thành": "به",
    "Thích ứng": "تطبیق",
    "thích ứng": "تطبیق",
    "tư duy": "تفکر",
    "Tư duy": "تفکر",
    "Tỷ lệ phần trăm": "درصد",
    "tỷ lệ phần trăm": "درصد",
    "Ghi đè": "بازنویسی",
    "ghi đè": "بازنویسی",
    "tiêu đề yêu cầu": "هدر درخواست",
    "Tiêu đề yêu cầu": "هدر درخواست",
    "Thay đổi ngôn ngữ": "تغییر زبان",
    "thay đổi ngôn ngữ": "تغییر زبان",
    "nhạy cảm": "حساس",
    "Nhạy cảm": "حساس",
    "không được hiển thị": "نمایش داده نمی‌شود",
    "Mẹo": "نکته",
    "mẹo": "نکته",
    "Chỉ hỗ trợ": "فقط پشتیبانی می‌کند",
    "chỉ hỗ trợ": "فقط پشتیبانی می‌کند",
    "sản phẩm": "محصول",
    "Sản phẩm": "محصول",
    "số tiền": "مبلغ",
    "Số tiền": "مبلغ",
    "cố định": "ثابت",
    "Cố định": "ثابت",
    "thiết lập sẵn": "از پیش تعیین شده",
    "Thiết lập sẵn": "از پیش تعیین شده",
    "trước": "قبل",
    "Trước": "قبل",
    "trang web": "وب‌سایت",
    "Trang web": "وب‌سایت",
    "vì vậy": "بنابراین",
    "Vì vậy": "بنابراین",
    "động": "پویا",
    "Động": "پویا",
    "tùy chỉnh": "سفارشی",
    "Tùy chỉnh": "سفارشی",
    "lấy": "گرفتن",
    "Lấy": "گرفتن",
    "bên dưới": "زیر",
    "Bên dưới": "زیر",
    "Đặt": "تنظیم",
    "đặt": "تنظیم",
    "này": "این",
    "Này": "این",
    "Giới thiệu": "معرفی",
    "giới thiệu": "معرفی",
    "đối tác": "شریک",
    "Đối tác": "شریک",
    "bạn": "شما",
    "Bạn": "شما",
    "luôn": "همیشه",
    "Luôn": "همیشه",
    "xứng đáng": "لیاق",
    "Xứng đáng": "لیاق",
    "chúng tôi": "ما",
    "Chúng tôi": "ما",
    "phấn đấu": "تلاش می‌کنیم",
    "Phấn đấu": "تلاش می‌کنیم",
    "đơn giản": "ساده",
    "Đơn giản": "ساده",
    "thẳng thắn": "صریح",
    "Thẳng thắn": "صریح",
    "riêng": "جداگانه",
    "Riêng": "جداگانه",
    "mỗi": "هر",
    "Mỗi": "هر",
    "chỉ": "فقط",
    "Chỉ": "فقط",
    "thích nghi": "سازگار",
    "Thích nghi": "سازگار",
    "agent": "عامل",
    "Agent": "عامل",
    "Euro": "یورو",
    "euro": "یورو",
    "an toàn": "امنیت",
    "An toàn": "امنیت",
    "Cách": "روش",
    "cách": "روش",
    "Chu kỳ": "دوره",
    "chu kỳ": "دوره",
    "tần suất": "فرکانس",
    "Tần suất": "فرکانس",
    "Phạt": "جریمه",
    "phạt": "جریمه",
    "giảm": "کاهش",
    "Giảm": "کاهش",
    "lặp lại": "تکرار",
    "Lặp lại": "تکرار",
    "từ": "کلمه",
    "trả về": "بازگشت",
    "Trả về": "بازگشت",
    "thay vì": "به جای",
    "Thay vì": "به جای",
    "Hạn ngạch": "سقف",
    "hạn ngạch": "سقف",
    "nhắc nhở": "یادآوری",
    "Nhắc nhở": "یادآوری",
    "truy vấn": "پرس‌وجو",
    "Truy vấn": "پرس‌وجو",
    "đầu": "ابتدا",
    "Đầu": "ابتدا",
    "đuôi": "انتها",
    "Đuôi": "انتها",
    "Trang chủ": "صفحه اصلی",
    "trang chủ": "صفحه اصلی",
    "Xác minh": "تأیید",
    "xác minh": "تأیید",
    "danh tính": "هویت",
    "Danh tính": "هویت",
    "Mã xác minh": "کد تأیید",
    "mã xác minh": "کد تأیید",
    "đã được gửi": "ارسال شد",
    "kiểm tra": "بررسی",
    "Kiểm tra": "بررسی",
    "Nâng cao": "پیشرفته",
    "nâng cao": "پیشرفته",
    "Danh sách đen": "لیست سیاه",
    "danh sách đen": "لیست سیاه",
    "khu vực": "منطقه",
    "Khu vực": "منطقه",
    "ví dụ": "مثال",
    "Ví dụ": "مثال",
    "thu gọn": "جمع کردن",
    "Thu gọn": "جمع کردن",
    "thanh bên": "نوار کناری",
    "Thanh bên": "نوار کناری",
    "mô hình kiểm tra": "مدل تست",
    "Mô hình kiểm tra": "مدل تست",
    "tin nhắn trợ lý": "پیام دستیار",
    "Tin nhắn trợ lý": "پیام دستیار",
    "tin nhắn người dùng": "پیام کاربر",
    "Tin nhắn người dùng": "پیام کاربر",
    "bổ sung": "تکمیلی",
    "Bổ sung": "تکمیلی",
    "hàng ngày": "روزانه",
    "Hàng ngày": "روزانه",
    "ngẫu nhiên": "تصادفی",
    "Ngẫu nhiên": "تصادفی",
    "phần thưởng": "جایزه",
    "Phần thưởng": "جایزه",
    "lấy": "دریافت",
    "Lấy": "دریافت",
    "ngay": "اکنون",
    "Ngay": "اکنون",
    "tích lũy": "انباشته",
    "Tích lũy": "انباشته",
    "tổng số": "مجموع",
    "Tổng số": "مجموع",
    "Thành công": "موفقیت",
    "lần": "بار",
    "chỉ có thể": "فقط می‌توان",
    "một lần": "یک بار",
    "không": "نه",
    "cho phép": "اجازه می‌دهد",
    "Cho phép": "اجازه می‌دهد",
    "Bật": "فعال کردن",
    "bật": "فعال کردن",
    "tính năng": "ویژگی",
    "Tính năng": "ویژگی",
    "Lưu ý": "توجه",
    "lưu ý": "توجه",
    "chỉ ảnh hưởng": "فقط تأثیر می‌گذارد",
    "cách": "نحوه",
    "ảnh hưởng": "تأثیر",
    "việc": "کار",
    "định tuyến": "مسیریابی",
    "thực tế": "واقعی",
    "Nếu cần": "اگر نیاز است",
    "nếu cần": "اگر نیاز است",
    "hành vi": "رفتار",
    "Hành vi": "رفتار",
    "thiết lập trong": "تنظیم در",
    "sau khi đóng": "بعد از بستن",
    "sẽ không còn": "دیگر نخواهد بود",
    "trình duyệt": "مرورگر",
    "Bạn có chắc": "آیا مطمئن هستید",
    "muốn": "می‌خواهید",
    "Tương thích": "سازگاری",
    "tương thích": "سازگاری",
    "phiên bản thử nghiệm": "نسخه بتا",
    "Phiên bản thử nghiệm": "نسخه بتا",
    "cấu trúc": "ساختار",
    "Cấu trúc": "ساختار",
    "có thể": "ممکن است",
    "xảy ra": "رخ دهد",
    "thay đổi": "تغییر",
    "Thay đổi": "تغییر",
    "tương lai": "آینده",
    "Tương lai": "آینده",
    "không dùng": "استفاده نکنید",
    "môi trường production": "محیط تولید",
    "chỉ định": "مشخص شده",
    "Chỉ định": "مشخص شده",
    "toàn bộ": "تمام",
    "Toàn bộ": "تمام",
    "Định dạng": "قالب‌بندی",
    "định dạng": "قالب‌بندی",
    "Bài kiểm tra": "تست",
    "bài kiểm tra": "تست",
    "không streaming": "غیر استریمینگ",
    "có thể": "ممکن است",
    "dựa vào": "بر اساس",
    "Dựa vào": "بر اساس",
    "Ánh xạ": "نگاشت",
    "ánh xạ": "نگاشت",
    "endpoint": "اندپوینت",
    
    # Additional common Vietnamese words
    "được thêm": "اضافه شده",
    "Được thêm": "اضافه شده",
    "trực tiếp": "مستقیم",
    "Trực tiếp": "مستقیم",
    "vào": "به",
    "Vào": "به",
    "Không": "نه",
    "chắc chắn": "مطمئن",
    "Chắc chắn": "مطمئن",
    "Tất cả": "همه",
    "tất cả": "همه",
    "Chỉ": "فقط",
    "Dùng": "استفاده",
    "dùng": "استفاده",
    "Chợ": "بازار",
    "chợ": "بازار",
    "mẫu": "الگو",
    "Mẫu": "الگو",
    "Chọn": "انتخاب",
    "chọn": "انتخاب",
    "Hiển thị": "نمایش",
}

def clean_text(text: str) -> str:
    """Clean text before translation"""
    if not isinstance(text, str):
        return text
    return text.strip()

def contains_placeholder(text: str) -> bool:
    """Check if text contains placeholders like {{...}}"""
    return bool(re.search(r'\{\{[^}]+\}\}', text))

def contains_url(text: str) -> bool:
    """Check if text contains URLs"""
    return bool(re.search(r'https?://', text))

def contains_code(text: str) -> bool:
    """Check if text contains code snippets"""
    patterns = [
        r'\{[\s\S]*?\}',  # JSON-like structures
        r'\n',  # Multiple lines
        r'[\[\]]',  # Brackets
    ]
    return any(re.search(pattern, text) for pattern in patterns)

def translate_word(word: str, translation_dict: Dict[str, str]) -> str:
    """Translate a single word using the dictionary"""
    # Try exact match first
    if word in translation_dict:
        return translation_dict[word]
    
    # Try lowercase match
    lower_word = word.lower()
    if lower_word in translation_dict:
        return translation_dict[lower_word]
    
    # Try capitalized match
    cap_word = word.capitalize()
    if cap_word in translation_dict:
        return translation_dict[cap_word]
    
    return word

def translate_text(text: str, translation_dict: Dict[str, str]) -> str:
    """Translate Vietnamese text to Persian using the dictionary"""
    if not isinstance(text, str):
        return text
    
    original_text = text
    
    # Sort translation dict by key length (longest first) for better matching
    sorted_translations = sorted(translation_dict.items(), key=lambda x: len(x[0]), reverse=True)
    
    # Try to translate phrases first
    for vi_phrase, fa_phrase in sorted_translations:
        if vi_phrase in text:
            text = text.replace(vi_phrase, fa_phrase)
    
    # Clean up multiple spaces
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    
    # If nothing was translated, return original
    if text == original_text:
        # Try word by word translation
        words = original_text.split()
        translated_words = [translate_word(word, translation_dict) for word in words]
        text = ' '.join(translated_words)
    
    return text

def translate_json_recursive(obj: Any, translation_dict: Dict[str, str]) -> Any:
    """Recursively translate JSON object"""
    if isinstance(obj, dict):
        result = {}
        for key, value in obj.items():
            # Keep keys as-is, only translate values
            result[key] = translate_json_recursive(value, translation_dict)
        return result
    elif isinstance(obj, list):
        return [translate_json_recursive(item, translation_dict) for item in obj]
    elif isinstance(obj, str):
        # Skip if contains code, JSON structures, or is very short
        if len(obj) <= 2 and not obj.isalpha():
            return obj
        
        # Preserve placeholders {{...}}
        placeholders = re.findall(r'\{\{[^}]+\}\}', obj)
        temp_text = obj
        for i, placeholder in enumerate(placeholders):
            temp_text = temp_text.replace(placeholder, f"___PLACEHOLDER_{i}___")
        
        # Translate
        translated = translate_text(temp_text, translation_dict)
        
        # Restore placeholders
        for i, placeholder in enumerate(placeholders):
            translated = translated.replace(f"___PLACEHOLDER_{i}___", placeholder)
        
        return translated
    else:
        return obj

def main():
    """Main translation function"""
    input_file = "/home/runner/work/new-api-fa/new-api-fa/web/src/i18n/locales/vi.json"
    output_file = "/home/runner/work/new-api-fa/new-api-fa/web/src/i18n/locales/fa.json"
    
    print(f"Loading Vietnamese JSON from: {input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        vi_data = json.load(f)
    
    print(f"Total keys to translate: {len(vi_data.get('translation', {}))}")
    
    print("Translating to Persian...")
    fa_data = translate_json_recursive(vi_data, TRANSLATION_DICT)
    
    print(f"Writing Persian JSON to: {output_file}")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(fa_data, f, ensure_ascii=False, indent=2)
    
    print(f"✓ Translation complete! {len(fa_data.get('translation', {}))} keys translated.")
    print(f"✓ Output saved to: {output_file}")

if __name__ == "__main__":
    main()
